-- Migration 004: Add scout brief and scout notes columns to creators.
--
-- scout_brief_short: 1-2 sentence punchy description for discovery cards.
--                    Auto-generated by the LLM brief generator script.
-- scout_brief_full:  3-5 sentence paragraph for the detail page.
--                    Auto-generated alongside scout_brief_short.
-- scout_notes:       Free-text operator overrides. NULL means "use the
--                    auto-generated brief." Non-NULL means "operator has
--                    written their own notes, use these instead."
--
-- All three are nullable. The dashboard falls back gracefully if a creator
-- doesn't yet have these populated (e.g., new creators from future harvests
-- before we run the brief generator).
--
-- Idempotent via IF NOT EXISTS.

ALTER TABLE creators
    ADD COLUMN IF NOT EXISTS scout_brief_short TEXT,
    ADD COLUMN IF NOT EXISTS scout_brief_full  TEXT,
    ADD COLUMN IF NOT EXISTS scout_notes       TEXT;
